version: '3'

services:
  fastapi:
    build: ./FastAPI/
    command: sh -c "sleep 110s ; uvicorn main_docker:app --reload"
    depends_on:
      - mysql

  mysql:
    build: ./mySQL_db/
    restart: always
#    command:
#      - '--secure-file-priv=""'
#      - '--local-infile=1'
    environment:
      MYSQL_DATABASE: 'ccf_mysql'
      MYSQL_ROOT_PASSWORD: 'Daniel'
    ports:
      - '3306:3306'
