version: '3'

services:
  fastapi:
    build: ./FastAPI/
    command: sh -c "sleep 90s ; uvicorn main_docker:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8000:8000
    networks:
      - my_network
    depends_on:
      - mysql

  mysql:
    build: ./mySQL_db/
    restart: always
#    command:
#      - '--secure-file-priv=""'
#      - '--local-infile=1'
    environment:
      MYSQL_DATABASE: 'ccf_mysql'
      MYSQL_ROOT_PASSWORD: 'Daniel'
    ports:
      - '3306:3306'
    networks:
      - my_network
networks:
  my_network:
    name: my_network
